[project]
authors = ["ikram98ai <ikram98ai@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "https://conda.modular.com/max", "https://repo.prefix.dev/modular-community", "conda-forge"]
name = "mojo-ml"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
max = "*"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
